[package]
name = "pregex"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.4"
pest_derive = "2.4"
itertools = "0.10"
env_logger = "0.9"
log = "0.4"
clap = { version = "3.0.0-beta.1" }
statrs = "0.16"